### ISSUE TITLE
Possible EventEmitter memory leak

### ISSUE THREAD

**Issue by nazariyv** [kenryu42/ethereum-nft-sales-bot#32]
### ENFT Version

1.0.5

### Describe the Problem

Thank you for this awesome library. This simplified so much work for collection creators.

This is somewhat a vague report, and not sure if this is a bug entirely either. When running ENFT via npm package on a local machine, everything works fine. The definition of works fine for me is: "It posts the sales to Discord".

However, when we package this up in a docker container and run on ecs on fargate, cloudwatch reports the following error:

```
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [FormData]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at FormData.addListener (node:events:605:10)
    at Stream.pipe (node:internal/streams/legacy:86:10)
    at CombinedStream.pipe (/app/node_modules/combined-stream/lib/combined_stream.js:65:25)
    at dispatchHttpRequest (file:///app/node_modules/axios/lib/adapters/http.js:645:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [FormData]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at FormData.addListener (node:events:605:10)
    at Stream.pipe (node:internal/streams/legacy:87:10)
    at CombinedStream.pipe (/app/node_modules/combined-stream/lib/combined_stream.js:65:25)
    at dispatchHttpRequest (file:///app/node_modules/axios/lib/adapters/http.js:645:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [FormData]. Use emitter.setMaxListeners() to increase limit
at _addListener (node:events:587:17)
at FormData.prependListener (node:events:619:14)
at prependListener (node:internal/streams/legacy:100:20)
at Stream.pipe (node:internal/streams/legacy:66:3)
at CombinedStream.pipe (/app/node_modules/combined-stream/lib/combined_stream.js:65:25)
at dispatchHttpRequest (file:///app/node_modules/axios/lib/adapters/http.js:645:12)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
file:///app/node_modules/axios/lib/core/AxiosError.js:89
AxiosError.call(axiosError, error.message, code, config, request, response);
^
AxiosError: socket hang up
at AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:577:25)
at RedirectableRequest.emit (node:events:525:35)
at eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
at ClientRequest.emit (node:events:513:28)
at TLSSocket.socketOnEnd (node:_http_client:526:9)
at TLSSocket.emit (node:events:525:35)
at endReadableNT (node:internal/streams/readable:1359:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
code: 'ECONNRESET',
config: {
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
},
adapter: [ 'xhr', 'http' ],
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
env: {
FormData: [Function: FormData] {
LINE_BREAK: '\r\n',
DEFAULT_CONTENT_TYPE: 'application/octet-stream'
},
Blob: [class Blob]
},
validateStatus: [Function: validateStatus],
headers: AxiosHeaders {
Accept: 'application/json, text/plain, */*',
'Content-Type': 'multipart/form-data; boundary=--------------------------116409738858655009138031',
'User-Agent': 'axios/1.3.4',
'Content-Length': '336452',
'Accept-Encoding': 'gzip, compress, deflate, br'
},
method: 'post',
url: 'https://discord.com/api/webhooks/<correct webhook id>',
data: FormData {
_overheadLength: 261,
_valueLength: 336191,
_valuesToMeasure: [],
writable: false,
readable: true,
dataSize: 0,
maxDataSize: 2097152,
pauseStreams: true,
_released: true,
_streams: [],
_currentStream: null,
_insideLoop: false,
_pendingNext: false,
_boundary: '--------------------------116409738858655009138031',
_events: [Object: null prototype] {
end: [
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
warned: true
],
error: [
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
[Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
warned: true
],
close: [
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
[Function (anonymous)],
warned: true
]
},
_eventsCount: 3
}
},
request: <ref *3> Writable {
_writableState: WritableState {
objectMode: false,
highWaterMark: 16384,
finalCalled: false,
needDrain: false,
ending: false,
ended: false,
finished: false,
destroyed: false,
decodeStrings: true,
defaultEncoding: 'utf8',
length: 0,
writing: false,
corked: 0,
sync: true,
bufferProcessing: false,
onwrite: [Function: bound onwrite],
writecb: null,
writelen: 0,
afterWriteTickInfo: null,
buffered: [],
bufferedIndex: 0,
allBuffers: true,
allNoop: true,
pendingcb: 0,
constructed: true,
prefinished: false,
errorEmitted: false,
emitClose: true,
autoDestroy: true,
errored: null,
closed: false,
closeEmitted: false,
[Symbol(kOnFinished)]: []
},
_events: [Object: null prototype] {
response: [Function: handleResponse],
error: [Function: handleRequestError],
socket: [Function: handleRequestSocket]
},
_eventsCount: 3,
_maxListeners: undefined,
_options: {
maxRedirects: 21,
maxBodyLength: Infinity,
protocol: 'https:',
path: '/api/webhooks/<correct webhook id>',
method: 'POST',
headers: [Object: null prototype] {
Accept: 'application/json, text/plain, */*',
'Content-Type': 'multipart/form-data; boundary=--------------------------116409738858655009138031',
'User-Agent': 'axios/1.3.4',
'Content-Length': '336452',
'Accept-Encoding': 'gzip, compress, deflate, br'
},
agents: { http: undefined, https: undefined },
auth: undefined,
beforeRedirect: [Function: dispatchBeforeRedirect],
beforeRedirects: { proxy: [Function: beforeRedirect] },
hostname: 'discord.com',
port: '',
agent: undefined,
nativeProtocols: {
'http:': {
_connectionListener: [Function: connectionListener],
METHODS: [
'ACL',         'BIND',       'CHECKOUT',
'CONNECT',     'COPY',       'DELETE',
'GET',         'HEAD',       'LINK',
'LOCK',        'M-SEARCH',   'MERGE',
'MKACTIVITY',  'MKCALENDAR', 'MKCOL',
'MOVE',        'NOTIFY',     'OPTIONS',
'PATCH',       'POST',       'PROPFIND',
'PROPPATCH',   'PURGE',      'PUT',
'REBIND',      'REPORT',     'SEARCH',
'SOURCE',      'SUBSCRIBE',  'TRACE',
'UNBIND',      'UNLINK',     'UNLOCK',
'UNSUBSCRIBE'
],
STATUS_CODES: {
'100': 'Continue',
'101': 'Switching Protocols',
'102': 'Processing',
'103': 'Early Hints',
'200': 'OK',
'201': 'Created',
'202': 'Accepted',
'203': 'Non-Authoritative Information',
'204': 'No Content',
'205': 'Reset Content',
'206': 'Partial Content',
'207': 'Multi-Status',
'208': 'Already Reported',
'226': 'IM Used',
'300': 'Multiple Choices',
'301': 'Moved Permanently',
'302': 'Found',
'303': 'See Other',
'304': 'Not Modified',
'305': 'Use Proxy',
'307': 'Temporary Redirect',
'308': 'Permanent Redirect',
'400': 'Bad Request',
'401': 'Unauthorized',
'402': 'Payment Required',
'403': 'Forbidden',
'404': 'Not Found',
'405': 'Method Not Allowed',
'406': 'Not Acceptable',
'407': 'Proxy Authentication Required',
'408': 'Request Timeout',
'409': 'Conflict',
'410': 'Gone',
'411': 'Length Required',
'412': 'Precondition Failed',
'413': 'Payload Too Large',
'414': 'URI Too Long',
'415': 'Unsupported Media Type',
'416': 'Range Not Satisfiable',
'417': 'Expectation Failed',
'418': "I'm a Teapot",
'421': 'Misdirected Request',
'422': 'Unprocessable Entity',
'423': 'Locked',
'424': 'Failed Dependency',
'425': 'Too Early',
'426': 'Upgrade Required',
'428': 'Precondition Required',
'429': 'Too Many Requests',
'431': 'Request Header Fields Too Large',
'451': 'Unavailable For Legal Reasons',
'500': 'Internal Server Error',
'501': 'Not Implemented',
'502': 'Bad Gateway',
'503': 'Service Unavailable',
'504': 'Gateway Timeout',
'505': 'HTTP Version Not Supported',
'506': 'Variant Also Negotiates',
'507': 'Insufficient Storage',
'508': 'Loop Detected',
'509': 'Bandwidth Limit Exceeded',
'510': 'Not Extended',
'511': 'Network Authentication Required'
},
Agent: [Function: Agent] { defaultMaxSockets: Infinity },
ClientRequest: [Function: ClientRequest],
IncomingMessage: [Function: IncomingMessage],
OutgoingMessage: [Function: OutgoingMessage],
Server: [Function: Server],
ServerResponse: [Function: ServerResponse],
createServer: [Function: createServer],
validateHeaderName: [Function: __node_internal_],
validateHeaderValue: [Function: __node_internal_],
get: [Function: get],
request: [Function: request],
setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
maxHeaderSize: [Getter],
globalAgent: [Getter/Setter]
},
'https:': {
Agent: [Function: Agent],
globalAgent: Agent {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
defaultPort: 443,
protocol: 'https:',
options: [Object: null prototype],
requests: [Object: null prototype] {},
sockets: [Object: null prototype],
freeSockets: [Object: null prototype] {},
keepAliveMsecs: 1000,
keepAlive: false,
maxSockets: Infinity,
maxFreeSockets: 256,
scheduling: 'lifo',
maxTotalSockets: Infinity,
totalSocketCount: 1,
maxCachedSessions: 100,
_sessionCache: [Object],
[Symbol(kCapture)]: false
},
Server: [Function: Server],
createServer: [Function: createServer],
get: [Function: get],
request: [Function: request]
}
},
pathname: '/api/webhooks/<correct webhook id>'
},
_ended: false,
_ending: false,
_redirectCount: 0,
_redirects: [],
_requestBodyLength: 0,
_requestBodyBuffers: [],
_onNativeResponse: [Function (anonymous)],
_currentRequest: <ref *1> ClientRequest {
_events: [Object: null prototype] {
response: [Function: bound onceWrapper] {
listener: [Function (anonymous)]
},
abort: [Function (anonymous)],
aborted: [Function (anonymous)],
connect: [Function (anonymous)],
error: [Function (anonymous)],
socket: [Function (anonymous)],
timeout: [Function (anonymous)]
},
_eventsCount: 7,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
destroyed: false,
_last: true,
chunkedEncoding: false,
shouldKeepAlive: false,
maxRequestsOnConnectionReached: false,
_defaultKeepAlive: true,
useChunkedEncodingByDefault: true,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
strictContentLength: false,
_contentLength: null,
_hasBody: true,
_trailer: '',
finished: false,
_headerSent: false,
_closed: false,
socket: <ref *2> TLSSocket {
_tlsOptions: {
allowHalfOpen: undefined,
pipe: false,
secureContext: SecureContext { context: SecureContext {} },
isServer: false,
requestCert: true,
rejectUnauthorized: true,
session: Buffer(1711) [Uint8Array] [
48, 130,   <a bunch more uint8s>,
... 1611 more items
],
ALPNProtocols: undefined,
requestOCSP: undefined,
enableTrace: undefined,
pskCallback: undefined,
highWaterMark: undefined,
onread: undefined,
signal: undefined
},
_secureEstablished: true,
_securePending: false,
_newSessionPending: false,
_controlReleased: true,
secureConnecting: false,
_SNICallback: null,
servername: 'discord.com',
alpnProtocol: false,
authorized: true,
authorizationError: null,
encrypted: true,
_events: [Object: null prototype] {
close: [
[Function: onSocketCloseDestroySSL],
[Function],
[Function: onClose],
[Function: socketCloseListener]
],
end: [ [Function: onReadableStreamEnd], [Function: socketOnEnd] ],
newListener: [Function: keylogNewListener],
secure: [Function: onConnectSecure],
session: [Function (anonymous)],
free: [Function: onFree],
timeout: [Function: onTimeout],
agentRemove: [Function: onRemove],
error: [Function: socketErrorListener],
data: [Function: socketOnData],
drain: [Function: ondrain]
},
_eventsCount: 11,
connecting: false,
_hadError: true,
_parent: null,
_host: 'discord.com',
_closeAfterHandlingError: false,
_readableState: ReadableState {
objectMode: false,
highWaterMark: 16384,

<!--EndFragment-->
</body>
</html>
```

For reference, the docker that we push to ECR is over here: https://github.com/rumble-kong-league/sales-bot.

The above error does not happen immediately after a sale. Rather after about 10 minutes from the first sale. I suspect it's because of the `retry` in your library, that tries to post the embed to discord multiple times. I doubt this error has anything to do with networking, since twitter posts work just fine on ecs on fargate.

What is slightly worrying is that it is making http requests, however discord webhook url is https.

This is running on v1CPU and 3GB RAM.

This happens on any collection.

**Comment by nazariyv** [comment]
Just noticed a new error in there:

Fontconfig error: Cannot load default config file: No such file: (null)

Adding a step to install fontconfig to dockerfile.

**Comment by nazariyv** [comment]
Nope, that wasn't it. Same errors around FormData.

**Comment by kenryu42** [comment]
Thanks for taking the time to report this issue. 

>  I suspect it's because of the retry in your library, that tries to post the embed to discord multiple times.

Do you have duplicate discord notifications? `retry` only attempts to post if it has previously failed.

Also, as the [readme](https://github.com/kenryu42/ethereum-nft-sales-bot#prerequisites) states, `fontconfig` is a prerequisite. It is not an error.

I will look into the `FormData` warning.

**Comment by nazariyv** [comment]
> Do you have duplicate discord notifications? retry only attempts to post if it has previously failed.

nope, it does not post anything if ran on ecs

**Comment by nazariyv** [comment]
updated the traceback with some more details. It starts off with even warnings, and then with a socket hang up after a while.

**Comment by nazariyv** [comment]
feel free to close this, I think it has something to do with ecs networking config...

I just tried this same bot on ec2 instances, and everything works fine.

**Comment by kenryu42** [comment]
I noticed that `FormData` was consuming more memory than expected. 
To address this, I removed the `form-data` package and switched to the native Node.js v18 FormData API in `version 1.0.6`. 

As a result, the memory usage was reduced almost by half. Make sure you are now using Node.js version `18` or higher. 

If you encounter any issues, please feel free to reach out.

**Comment by nazariyv** [comment]
Brilliant, thank you!
