### ISSUE TITLE
Error when tx.isSweep > 3

### ISSUE THREAD

**Issue by delta0800** [kenryu42/ethereum-nft-sales-bot#5]
2022-07-31T06:52:47: Error: Given file is not valid, please check its type.
2022-07-31T06:52:47:     at getFileHandle (/www/wwwroot/wBot/ethereum-nft-sales-bot/node_modules/twitter-api-v2/dist/v1/media-helpers.v1.js:61:15)
2022-07-31T06:52:47:     at TwitterApiv1.getUploadMediaRequirements (/www/wwwroot/wBot/ethereum-nft-sales-bot/node_modules/twitter-api-v2/dist/v1/client.v1.write.js:352:69)
2022-07-31T06:52:47:     at TwitterApiv1.uploadMedia (/www/wwwroot/wBot/ethereum-nft-sales-bot/node_modules/twitter-api-v2/dist/v1/client.v1.write.js:285:78)
2022-07-31T06:52:47:     at tweet (file:///www/wwwroot/wBot/ethereum-nft-sales-bot/twitter/tweet.js:43:35)
2022-07-31T06:52:47:     at runApp (file:///www/wwwroot/wBot/ethereum-nft-sales-bot/controllers/runApp.js:63:15)
2022-07-31T06:52:47:     at runMicrotasks (<anonymous>)
2022-07-31T06:52:47:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-07-31T06:52:47:     at async Subscription.<anonymous> (file:///www/wwwroot/wBot/ethereum-nft-sales-bot/app.js:49:17)

**Comment by kenryu42** [comment]
Hi. Could you please provide the `contract address` and `transaction hash` that caused this error?

**Comment by delta0800** [comment]
Sir, below are the details. Thanks

Contract address: 0xdbd82CaBc57631d267545C4b1627558B53dfC4c4
Transcation hash: 0x7db3c25efc9ae6c5e1cd68eb7fb88b7255d3be431f36a2196ac372a541753800

Contract address: 0xC86664e7d2608f881f796ee8E24FA9d4d7598406
Transcation hash: 0x1c765d0b92ff112eda6e5316ca7b3f7dbe0a54f39d5b058cc2b74a92e910ce9d

**Comment by kenryu42** [comment]
> 

Both examples work fine for me.

If you use `Alchemy` as your default NFT Api, their image cache may be out of date for some unpopular collections. You will need to request the api multiple times to force a metadata refresh or [manually trigger a metadata refresh](https://docs.alchemy.com/alchemy/enhanced-apis/nft-api/reingestcontract) .

`Opensea` Api should be fine in this case.

**Comment by delta0800** [comment]
I noticed issue about the Alchemy metadata api, i am using opensea api now. May i know what version of Node you are running? Currently i am at v16.13.2 . Create Gif not working for me.

**Comment by kenryu42** [comment]
> I noticed issue about the Alchemy metadata api, i am using opensea api now. May i know what version of Node you are running? Currently i am at v16.13.2 . Create Gif not working for me.

I am using `v16.16.0` LTS.
Let me know if the node version update fixes the problem.

**Comment by delta0800** [comment]
Okay i will try with v16.16. Update to you again.

**Comment by delta0800** [comment]
It`s working now mate. Thanks and appreciated it. Currently running on v16.16 and previously failed to create gif due to permission denied error.
